name: Check Instagram Follow Requests

on:
  schedule:
    - cron: "*/10 * * * *" # Every 10 minutes
  workflow_dispatch:

jobs:
  check-requests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager instagrapi python-dotenv
          pip install -r requirements.txt

      - name: Create config directory
        run: mkdir -p config

      - name: Generate config file
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
          ICLOUD_EMAIL: ${{ secrets.ICLOUD_EMAIL }}
          ICLOUD_PASSWORD: ${{ secrets.ICLOUD_PASSWORD }}
        run: |
          cat << 'EOF' > config/config.ini
          [instagram]
          username = ${INSTAGRAM_USERNAME}
          password = ${INSTAGRAM_PASSWORD}

          [email]
          smtp_server = smtp.mail.me.com
          smtp_port = 587
          email = ${ICLOUD_EMAIL}
          password = ${ICLOUD_PASSWORD}
          recipient_email = rujuldwivedi@icloud.com

          [selenium]
          headless = True
          EOF

          echo "Config file created successfully:"
          cat config/config.ini

      - name: Run Instagram checker
        run: |
          # Debug directory structure
          echo "Current directory structure:"
          ls -R

          # Run the script with explicit Python call
          python src/main.py

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-logs
          path: |
            *.log
            debug.png
