name: Check Instagram Follow Requests

on:
  schedule:
    - cron: "*/10 * * * *" # Every 10 minutes
  workflow_dispatch:

jobs:
  check-requests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Create config directory
        run: mkdir -p config # Add this step to create the directory

      - name: Run Instagram checker
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
          ICLOUD_EMAIL: ${{ secrets.ICLOUD_EMAIL }}
          ICLOUD_PASSWORD: ${{ secrets.ICLOUD_PASSWORD }}
        run: |
          python -c "
          import os
          from configparser import ConfigParser

          # Create config file from environment variables
          config = ConfigParser()
          config['instagram'] = {
              'username': os.environ['INSTAGRAM_USERNAME'],
              'password': os.environ['INSTAGRAM_PASSWORD']
          }
          config['email'] = {
              'smtp_server': 'smtp.mail.me.com',
              'smtp_port': '587',
              'email': os.environ['ICLOUD_EMAIL'],
              'password': os.environ['ICLOUD_PASSWORD'],
              'recipient_email': 'rujuldwivedi@icloud.com'
          }
          config['selenium'] = {
              'headless': 'True'
          }

          os.makedirs('config', exist_ok=True)  # Ensure directory exists
          with open('config/config.ini', 'w') as f:
              config.write(f)
          "
          python src/main.py
