name: Check Instagram Follow Requests

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  check-requests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          
      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          
          # Install latest stable Chrome
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          
          # Install matching ChromeDriver using webdriver-manager
          python -m pip install webdriver-manager
          python -c "from webdriver_manager.chrome import ChromeDriverManager; ChromeDriverManager().install()"
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          
      - name: Run Instagram checker
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
          ICLOUD_EMAIL: ${{ secrets.ICLOUD_EMAIL }}
          ICLOUD_PASSWORD: ${{ secrets.ICLOUD_PASSWORD }}
        run: |
          python src/main.py \
            --instagram-username "$INSTAGRAM_USERNAME" \
            --instagram-password "$INSTAGRAM_PASSWORD" \
            --email "$ICLOUD_EMAIL" \
            --email-password "$ICLOUD_PASSWORD" \
            --recipient-email "rujuldwivedi@icloud.com"