name: Check Instagram Follow Requests

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  check-requests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          
      - name: Install dependencies
        run: |
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install selenium webdriver-manager

      - name: Run Instagram checker
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
          ICLOUD_EMAIL: ${{ secrets.ICLOUD_EMAIL }}
          ICLOUD_PASSWORD: ${{ secrets.ICLOUD_PASSWORD }}
        run: |
          python src/main.py \
            --instagram-username "$INSTAGRAM_USERNAME" \
            --instagram-password "$INSTAGRAM_PASSWORD" \
            --email "$ICLOUD_EMAIL" \
            --email-password "$ICLOUD_PASSWORD" \
            --recipient-email "rujuldwivedi@icloud.com"